data_ingestion:
  bucket_name : "my_bucket16062025"
  bucket_file_name : "framingham.csv"
  train_ratio : 0.8


data_processing:
  categorical_columns: []
  numerical_columns:
    - male
    - age
    - education
    - currentSmoker
    - cigsPerDay
    - BPMeds
    - prevalentStroke
    - prevalentHyp
    - diabetes
    - totChol
    - sysBP
    - diaBP
    - BMI
    - heartRate
    - glucose
  skewness_threshold: 5
  no_of_features: 10